all: main.cpp
	g++ -o test main.cpp -L/home/kanwu/vcpkg/installed/x64-linux/lib -lazurestorage -lcpprest -lboost_system -lboost_log -lboost_log_setup -lboost_thread -lboost_serialization -luuid -lxml2 -lz -llzma -lssl -lcrypto -lpthread -ldl -I /home/kanwu/vcpkg/installed/x64-linux/include
